#!/bin/bash

## This script is for near-real-time and periodic fixes, etc.

if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

chmod +x /etc/rc.local

source /usr/local/sbin/.wpsd-common-funcs

gitUaStr="Server-Side Slipstream Task $uaStr"

EXCLUDED_CALLS=("W0CHP" "M1ABC" "N0CALL" "NOCALL" "PE1XYZ" "PE1ABC" "")
FOUND_MATCH=""
if [[ " ${EXCLUDED_CALLS[@]} " =~ " ${CALL} " ]]; then
    :
else
    if grep -q -ri -- '-cron' /usr/local/sbin; then
        FOUND_MATCH="Matched: '-cron' in /usr/local/sbin"
    elif grep -q -r '/api/v1/repos' /usr/local/sbin; then
        FOUND_MATCH="Matched: 'Old API' in /usr/local/sbin"
    elif grep -q -r 'hwDeetz' /usr/local/sbin; then
        FOUND_MATCH="Matched: 'hwDeetz' in /usr/local/sbin"
    elif grep -q -r 'sbin check' /usr/local/sbin; then
        FOUND_MATCH="Matched: 'sbin check' in /usr/local/sbin"
    elif grep -q -r 'sbin update' /usr/local/sbin; then
        FOUND_MATCH="Matched: 'sbin update' in /usr/local/sbin"
    elif grep -q -r 'getDVModemFirmware' /usr/local/sbin; then
        FOUND_MATCH="Matched: 'getDVModemFirmware' in /usr/local/sbin"
    elif grep -q 'ConnCheck' /usr/local/sbin/wpsd-hostfile-update; then
        FOUND_MATCH="Matched: 'ConnCheck' in /usr/local/sbin/wpsd-hostfile-update"
    elif grep -q 'pistar-css-W0CHP.ini' /var/www/dashboard/css/css-base.php; then
        FOUND_MATCH="Matched: 'pistar-css-W0CHP.ini' in /var/www/dashboard/css/css-base.php"
    #elif ! grep -q 'OptIntoUserMap' /etc/WPSD-Dashboard-Config.ini; then
    #    FOUND_MATCH="Missing: 'OptIntoUserMap' in /etc/WPSD-Dashboard-Config.ini"
    elif [ -f '/usr/local/sbin/.wpsd-diags' ]; then
        FOUND_MATCH="Matched: Legacy Diags"
    elif [ ! -d '/var/www/dashboard/.git' ] ; then
	FOUND_MATCH="Matched: missing dashboard"
    elif [ ! -d '/usr/local/sbin/.git' ] ; then
	FOUND_MATCH="Matched: missing sbin"
    elif [ ! -d '/usr/local/bin/.git' ] ; then
	FOUND_MATCH="Matched: missing bin"
    fi

    if [[ -n "$FOUND_MATCH" ]]; then
        curl -Ls -A "server-side Slipstream Task PH00 reset ${uaStr} ${FOUND_MATCH}" https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Scripts/raw/branch/master/reset-wpsd | sudo bash
	exit 0
    fi
fi

# set global DVM cast var
castResult=$(isDVmegaCast)

# 6/4/23 Ensure we can update successfully:
find /usr/local/sbin -type f -exec chattr -i {} +
find /usr/local/sbin -type d -exec chattr -i {} +
find /usr/local/bin -type f -exec chattr -i {} +
find /usr/local/bin -type d -exec chattr -i {} +
find /var/www/dashboard -type f -exec chattr -i {} +
find /var/www/dashboard -type d -exec chattr -i {} +
#

# 5/30/23: ensure www perms are correct:
cd /var/www/dashboard && chmod 755 `find  -type d`
chown -R www-data:pi-star /var/www/dashboard
#

# profile manager cleanups and updates
find /etc/WPSD_config_mgr/ -type f -name "*.php" -exec rm -f {} +
config_value=$(cat /etc/.WPSD_config)
target_dir="/etc/WPSD_config_mgr/$config_value"
target_file="$target_dir/WPSD-Dashboard-Config.ini"
if [[ ! -f "$target_file" ]]; then
  cp /etc/WPSD-Dashboard-Config.ini "$target_file" > /dev/null 2>&1
fi

# ensure perms for git repos
if ! grep -q 'safe' /root/.gitconfig > /dev/null 2>&1 ; then
    git config --global --add safe.directory /var/www/dashboard > /dev/null 2>&1
    rm -rf /var/www/dashboard/.git/index.lock
    git config --global --add safe.directory /usr/local/bin > /dev/null 2>&1
    rm -rf /usr/local/bin/.git/index.lock
    git config --global --add safe.directory /usr/local/sbin > /dev/null 2>&1
    rm -rf /usr/local/sbin/.git/index.lock
fi

# dvmega cast-specific stuff
if [ "$castResult" == "true" ]; then
    if ! grep -q 'cast' /root/.gitconfig > /dev/null 2>&1 ; then
	git config --global --add safe.directory /opt/cast > /dev/null 2>&1
    fi
fi

# rc.local
if grep -q 'wpsd-sys-cache' /etc/rc.local ; then
    sed -i 's|# cache hw info|# start running tasks|; s|/usr/local/sbin/.wpsd-sys-cache|systemctl start wpsd-running-tasks.service|' /etc/rc.local
fi

# Git repo name changes/migrations
#
# 5/2024 - W0CHP
#
update_git_remotes() {
    if [ "$#" -lt 2 ]; then
        #echo "Usage: update_git_remotes <dir1> <url1> [<dir2> <url2> ...] [remote-name]"
        return 1
    fi

    # Get the remote name (default to 'origin')
    remote_name=${!#}
    if [[ ! $remote_name =~ ^[a-zA-Z0-9]+$ ]]; then
        remote_name="origin"
    else
        # Exclude the last argument from the directories list
        set -- "${@:1:$(($#-1))}"
    fi

    # Iterate over the pairs of directory and URL arguments
    while (( "$#" >= 2 )); do
        dir=$1
        new_remote_url=$2

        if [ -d "$dir/.git" ]; then
            #echo "Checking remote URL in $dir..."
            current_remote_url=$(git -C "$dir" remote get-url "$remote_name")
            if [ "$current_remote_url" != "$new_remote_url" ]; then
                #echo "Updating remote URL in $dir from $current_remote_url to $new_remote_url..."
                git -C "$dir" remote set-url "$remote_name" "$new_remote_url"
                #echo "Updated $dir"
            else
                #echo "Skipping $dir: Remote URL is already set to $new_remote_url"
		:
            fi
        else
            #echo "Skipping $dir: Not a git repository"
	    :
        fi

        # Shift past the current directory and URL
        shift 2
    done

    #echo "All specified repositories checked."
}

# Now update the repo remote URLs if needed
update_git_remotes /var/www/dashboard https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-WebCode.git /usr/local/bin https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Binaries.git /usr/local/sbin https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Scripts.git
#

# Tweak shelliniabox/web ssh colors:
#
# 10/2023 - W0CHP
if ! grep -q "Terminal.css" "/etc/default/shellinabox"; then
    sed -i 's/SHELLINABOX_ARGS=.*$/SHELLINABOX_ARGS="--no-beep --disable-ssl-menu --disable-ssl --css=\/etc\/shellinabox\/options-enabled\/00_White\\ On\\ Black.css --css=\/etc\/shellinabox\/options-enabled\/01+Color\\ Terminal.css"/' /etc/default/shellinabox
    systemctl restart shellinabox.service
fi
# 

# migrate legacy network info URLs
# 
# 10/23 W0CHP
files=(
  /etc/dmrgateway
  /etc/ysfgateway
  /etc/p25gateway
  /etc/nxdngateway
  /etc/ircddbgateway
  /etc/m17gateway
  /etc/mmdvmhost
  /etc/nxdn2dmr
  /etc/ysf2dmr
  /etc/ysf2nxdn
  /etc/ysf2p25
  /etc/WPSD_config_mgr/*/*
)

old_url="http://www.mw0mwz.co.uk/pi-star/"
new_url="https://wpsd.radio"

for file in "${files[@]}"; do
  if [[ -f "$file" ]]; then
    if grep -qi "$old_url" "$file"; then
      file_content=$(<"$file")
      
      if [[ $file_content == *'URL='* || $file_content == *'url='* ]]; then
        new_content="${file_content//URL=/URL=}"
        new_content="${new_content//url=/url=}"
        new_content="${new_content//$old_url/$new_url}"

        # Only write back if content changed
        if [[ "$file_content" != "$new_content" ]]; then
          echo -n "$new_content" > "$file"
          echo "Updated URL in $file"
        fi
      fi
    fi
  fi
done
for file in "${files[@]}"; do
  if [[ -f "$file" ]]; then
    file_content=$(<"$file")
    new_content="${file_content//_W0CHP-PiStar-Dash/_WPSD}"

    # Only write back if content changed
    if [[ "$file_content" != "$new_content" ]]; then
      echo -n "$new_content" > "$file"
      echo "Updated _W0CHP-PiStar-Dash in $file"
    fi
  fi
done
#

# Git URI changed when transferring repos from me to the org.
#
# 2/2023 - W0CHP
#
function gitURIupdate () {
    dir="$1"
    gitRemoteURI=$(git --work-tree=${dir} --git-dir=${dir}/.git config --get remote.origin.url)

    git --work-tree=${dir} --git-dir=${dir}/.git config --get remote.origin.url | grep 'WPSD-Dev' &> /dev/null
    if [ $? == 0 ]; then
        newURI=$( echo $gitRemoteURI | sed 's|repo\.w0chp\.net/WPSD-Dev|wpsd-swd.w0chp.net/WPSD-SWD|g' )
        git --work-tree=${dir} --git-dir=${dir}/.git remote set-url origin $newURI
    fi
}
gitURIupdate "/var/www/dashboard"
gitURIupdate "/usr/local/bin"
gitURIupdate "/usr/local/sbin"
if [ "$castResult" == "true" ]; then
    gitURIupdate "/opt/cast"
fi
#

SERVICE_NAME="mmdvmhost.service"
STATUS=$(systemctl is-enabled "$SERVICE_NAME" 2>/dev/null)
if [[ "$STATUS" == "enabled" ]]; then
    systemctl disable mmdvmhost.service > /dev/null 2>&1
fi


# default loc.
FILE="/etc/mmdvmhost"
if (grep -q "Latitude=50.0" "$FILE" && grep -q "Longitude=-3.00" "$FILE") || \
   (grep -q "Latitude=44.127691" "$FILE" && grep -q "Longitude=91.762659" "$FILE"); then
    sed -i 's/Latitude=50.0/Latitude=0.0/g' "$FILE"
    sed -i 's/Longitude=-3.00/Longitude=0.0/g' "$FILE"
    sed -i 's/Latitude=44.127691/Latitude=0.0/g' "$FILE"
    sed -i 's/Longitude=91.762659/Longitude=0.0/g' "$FILE"
fi
# placeholder for malformed coords (ugh...users :-/)
NEW_LAT="0.0"
NEW_LONG="0.0"
TMP_FILE=$(mktemp)
sed -E '
  # Match Latitude= lines and validate the value
  /Latitude=/ {
    # If Latitude does not contain exactly one decimal point, or contains commas, replace it
    /Latitude=[^0-9]*([0-9]+,|[^.]*\.[^0-9]*\.[^0-9]*)/ {
      s|Latitude=.*|Latitude='"$NEW_LAT"'|
    }
    # If Latitude contains no decimal point, replace it
    /Latitude=[^0-9]*[0-9]+$/ {
      s|Latitude=.*|Latitude='"$NEW_LAT"'|
    }
  }
  # Match Longitude= lines and validate the value
  /Longitude=/ {
    # If Longitude does not contain exactly one decimal point, or contains commas, replace it
    /Longitude=[^0-9]*([0-9]+,|[^.]*\.[^0-9]*\.[^0-9]*)/ {
      s|Longitude=.*|Longitude='"$NEW_LONG"'|
    }
    # If Longitude contains no decimal point, replace it
    /Longitude=[^0-9]*[0-9]+$/ {
      s|Longitude=.*|Longitude='"$NEW_LONG"'|
    }
  }
' "$FILE" > "$TMP_FILE"
if ! cmp -s "$TMP_FILE" "$FILE"; then
  mv "$TMP_FILE" "$FILE"
  chmod 644 "$FILE"
fi

# 5/2023 W0CHP
#
# Armbian:
if [ "${OS_VER}" -gt "10" ] && [ -f '/boot/armbianEnv.txt' ] && [[ ! $(grep "net.ifnames" /boot/armbianEnv.txt) ]] ; then
    sed -i '$ a\extraargs=net.ifnames=0' /boot/armbianEnv.txt
fi
#

# 01/08/24: no BT:
if [ -f '/etc/bluetooth/input.conf' ] ; then
    apt-get remove -y --purge bluez pi-bluetooth bluez-firmware
    apt-get autoremove -y
fi

#  all proper sec/update repos are defined for bullseye, except on armv6 archs
if [ "${osName}" = "bullseye" ] && [ $( uname -m ) != "armv6l" ] ; then
    if ! grep -q 'bullseye-security' /etc/apt/sources.list ; then
        if ! apt-key list | grep -q "Debian Security Archive Automatic Signing Key (11/bullseye)" > /dev/null 2>&1; then
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 54404762BBB6E853 > /dev/null 2>&1
        fi
        echo "deb http://security.debian.org/debian-security bullseye-security main contrib non-free" >> /etc/apt/sources.list
    fi
    if ! grep -q 'bullseye-updates' /etc/apt/sources.list  ; then
        if ! apt-key list | grep -q "Debian Archive Automatic Signing Key (11/bullseye)" > /dev/null 2>&1 ; then
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0E98404D386FA1D9 > /dev/null 2>&1
        fi
        echo "deb http://deb.debian.org/debian bullseye-updates main contrib non-free" >> /etc/apt/sources.list
    fi
fi
# Bulleye backports, etc. cause php-fpm segfaults on armv6 (Pi 0w 1st gen) archs...
# So we'll stick with the "normal" repos for these archs (retro buster image bugfix)
if [ $( uname -m ) == "armv6l" ] ; then
    if grep -q 'bullseye-security' /etc/apt/sources.list ; then
        sed -i '/bullseye-security/d' /etc/apt/sources.list
        sed -i '/bullseye-updates/d' /etc/apt/sources.list
        apt-get remove --purge -y php7.4*
        apt-get clean ; apt autoclean
        apt-get update
        apt-get install -y php7.4-fpm php7.4-readline php7.4-mbstring php7.4-cli php7.4-zip php7.4-opcache
        systemctl restart php7.4-fpm
    fi
fi
#

# Armbian for NanoPi Neo / OrangePi Zero handling..
if [ -f "$armbian_env_file" ] && [[ $(grep "console=serial" $armbian_env_file) ]] ; then
    sed -i '/console=serial/d' $armbian_env_file
    if [ -f '/etc/network/if-pre-up.d/static-mac' ] ; then
	rm -rf /etc/network/if-pre-up.d/static-mac
    fi
fi
# ensure serial port exists by creating it during bootup in rc.local...
ttyama0_line="# OPi/NanoPi serial ports:"
ttyama0_line+="\nmknod \"/dev/ttyAMA0\" c 4 65"
ttyama0_line+="\nchown .dialout /dev/ttyAMA0"
ttyama0_line+="\nchmod 660 /dev/ttyAMA0\n"
ssh_keys_line="# AutoGenerate SSH keys if they are missing"
if [ -f "$armbian_env_file" ] && ! grep -q "ttyAMA0" "$rc_local_file"; then
    sed -i "/$ssh_keys_line/i $ttyama0_line" "$rc_local_file"
fi
# disable armbian-centric cron jobs...
cronfiles=(
    "/etc/cron.d/armbian-truncate-logs"
    "/etc/cron.d/armbian-check-battery"
    "/etc/cron.d/armbian-updates"
    "/etc/cron.weekly/armbian-quotes"
    "/etc/cron.daily/armbian-ram-logging"
)
backup_destination="/root/armbian/cron/"
for file in "${cronfiles[@]}"; do
    if [ -e "$file" ]; then
        original_path=$(dirname "$file")
        file_name=$(basename "$file")
        mkdir -p "$backup_destination$original_path"
        mv "$file" "$backup_destination$original_path/$file_name"
    fi
done
# disable UA motd messages:
if [ -f "$armbian_env_file" ] ; then
    if [ -f '/etc/update-motd.d/92-unattended-upgrades' ] ; then
	mkdir -p /root/armbian/etc_update-motd.d
	mv /etc/update-motd.d/92-unattended-upgrades /root/armbian/etc_update-motd.d
    fi
fi
# disable armbian zram
if [ -f "$armbian_env_file" ] ; then
    if ! `systemctl status armbian-zram-config.service | grep -q masked` ; then
	systemctl stop armbian-zram-config.service
	systemctl disable armbian-zram-config.service
	systemctl mask armbian-zram-config.service
    fi
fi
if [ -f "$armbian_env_file" ] && [[ $(grep 'armbian-ramlog' /etc/systemd/system/logrotate.service) ]] ; then
    sed -i '/armbian-ramlog/d' /etc/systemd/system/logrotate.service
    rm -rf /var/log.hdd
    systemctl daemon-reload
    systemctl restart logrotate.service
fi
# setup armbian holds for unattended ups...
if [ -f "$armbian_env_file" ]; then
    apt-mark hold \
	base-files \
	hostapd \
        armbian-bsp-cli-nanopineo-current \
        armbian-bsp-cli-nanopineo \
        linux-u-boot-nanopineo-edge \
        armbian-bsp-cli-orangepizero \
        linux-dtb-edge-sunxi \
        linux-image-edge-sunxi \
        linux-u-boot-orangepizero-edge \
        armbian-firmware-full \
        armbian-firmware > /dev/null 2>&1
fi
# cleanup NanoPi/OPi modprobing
if [ -f "$armbian_env_file" ] && [[ $(grep 'modprobe -r rtl8' $rc_local_file) ]] ; then
    sed -i '/modprobe -r rtl8/d' $rc_local_file
fi
if [ -f "$armbian_env_file" ] && [[ $(grep 'modprobe -r leds_' $rc_local_file) ]] ; then
    sed -i '/modprobe -r leds_/d' $rc_local_file
fi
# repo migration : 1/23/24 W0CHP
if [ -f "$armbian_env_file" ] ; then
    if grep -q 'beta' /etc/apt/sources.list.d/armbian.list ; then
	sed -i 's/beta\.armbian\.com/apt.armbian.com/g' /etc/apt/sources.list.d/armbian.list
    fi
fi
# random eth0 mac fix/reversion for new Nano/Orange Pi DTBs: 8/24 W0CHP
if [ -f "$armbian_env_file" ] ; then
    if grep -q 'ethaddr' $armbian_env_file ; then
	sed -i '/ethaddr/d' $armbian_env_file
	#reboot
    fi
    if [ -f "/etc/network/if-pre-up.d/static-mac" ] ; then
	rm -rf /etc/network/if-pre-up.d/static-mac
	#reboot
    fi
fi
# get more modern kernel and dtb's for NanoPi in DVM casts & euronodes; 8/24 W0CHP
if [ -f "$armbian_env_file" ] ; then
    if dpkg-query -l | grep -q "nanopi" ; then
        if grep -q "dvmpi" /etc/dstar-radio.mmdvmhost ; then
            if uname -r | grep -q "6.6." ; then
                apt update
                apt -y autoremove
                apt -y clean
                apt -y autoclean
                apt -y upgrade
                apt -y remove --purge --allow-change-held-packages linux-u-boot-nanopineo-edge linux-image-edge-sunxi linux-dtb-edge-sunxi
                apt -y install --reinstall --allow-change-held-packages linux-u-boot-nanopineo-edge linux-image-edge-sunxi linux-dtb-edge-sunxi
                apt -y autoremove
                apt -y clean
                apt -y autoclean
                reboot
            fi
        fi
    fi
fi

# ensure gpsd is only enabled by the user:
if ! `systemctl status gpsd.socket | grep -q masked` && [ `sed -n '/^\[GPSD\]/,/^\[/p' /etc/dmrgateway | grep "^Enable" | awk -F '=' '{print $2}'` == 0 ] ; then
    systemctl stop gpsd.service > /dev/null 2>&1
    systemctl stop gpsd.socket > /dev/null 2>&1
    systemctl disable gpsd.service > /dev/null 2>&1
    systemctl disable gpsd.socket > /dev/null 2>&1
    systemctl mask gpsd.service > /dev/null 2>&1
    systemctl mask gpsd.socket > /dev/null 2>&1
fi

# NanoPi/OPi/Armbian vnstat & late-init wlan handling:
if [ -f "$armbian_env_file" ] ; then
    if ip link show eth0 | grep -q "state UP" ; then
	:
    else 
	# Check if there's an active network connection on wlan0
	if ip link show wlan0 | grep -q "state UP" ; then
	    # Check if the error message is present for wlan0
	    if vnstat -i wlan0 2>&1 | grep -q "Error: Interface \"wlan0\" not found in database." ; then
		service vnstat stop
		rm -f /var/lib/vnstat/*
		service vnstat start
	    fi
	fi
    fi
fi

# retro. m17gateway ini malformed callsign fix:
file_path="/etc/m17gateway"
invalid_lines=$(awk -F'=' '/Callsign=.*-($| )|Callsign=.* / {print NR, $0}' "$file_path")
if [ -n "$invalid_lines" ]; then
    sed -i 's/\(Callsign=.*\)-$/\1/; s/\(Callsign=.*\)- /\1/; s/\(Callsign=.*\) $/\1/' "$file_path"
fi

# cleanup DMRgw X-mode decrips...
if grep -q '_Cross-over' /etc/dmrgateway ; then
    sed -i 's/_Cross-over/_Cross-Mode/g' /etc/dmrgateway
fi

# use WPSD TG as sample in ysf2dmr
if grep -q 'StartupDstId=31672' /etc/ysf2dmr ; then
    sed -i 's/StartupDstId=31672/StartupDstId=3170603/g' /etc/ysf2dmr
fi

#
# placeholder dapnet api file if it doesn't exst
# 1/17/2024 - W0CHP
#
dapnet_key="/etc/dapnetapi.key"
if [ ! -e "$dapnet_key" ]; then
    # If the file does not exist, create it with the specified contents
    echo "[DAPNETAPI]" > "$dapnet_key"
    echo "USER=" >> "$dapnet_key"
    echo "PASS=" >> "$dapnet_key"
    echo "TRXAREA=" >> "$dapnet_key"
    echo "MY_RIC=" >> "$dapnet_key"
fi
#

#
# close the py2 coffin
# 1/25/2024 - W0CHP
#
if [ "${OS_VER}" -lt "12" ] ; then # only for bullseye
    if dpkg -l | grep -q python-configparser; then
	:
    else
	apt-get update
	apt-get install -y python-configparser
    fi
fi
if dpkg -l | grep -q python-is-python3; then
    :
else
    apt-get update
    apt-get install -y python-is-python3
fi

#
# htpasswd bookworm
# 6/2024 - W0CHP
#
if [ ! -f /usr/bin/htpasswd ] ; then
    apt-get update
    apt-get install -y apache2-utils
fi
#

# upnp bookworm
# 6/2024 - W0CHP
#
if [ ! -f /usr/bin/upnpc ] ; then
    apt-get update
    apt-get install -y miniupnpc
    systemctl restart pistar-upnp.service
fi
#

#
# disable BT in BW - 2/12/2024 W0CHP
#
if [ "${OS_VER}" -ge "12" ] ; then
    if ! grep -q 'toverlay=disable-bt' /boot/firmware/config.txt ; then
        sed -i '/\[all\]/a dtoverlay=disable-bt' /boot/firmware/config.txt
    fi
fi
#

# No such modem "genesis.*" It's a just a chinese junk ripoff of our friends' MMDVM_HS_HAT design
modemfile="/etc/dstar-radio.mmdvmhost"
if grep -q "genesis" "$modemfile"; then
    sed -i 's/Hardware=.*/Hardware=mmdvmhshat/g' "$modemfile"
fi
if grep -q "genesys" "$modemfile"; then
    sed -i 's/Hardware=.*/Hardware=mmdvmhshat/g' "$modemfile"
fi

# dvmega cast-specific stuff
if [ "$castResult" == "true" ]; then
    # ensure avrdude conf. is installed for radio/hotspot mgmt.
    if [ ! -f '/etc/avrdude.conf' ] ; then
	declare -a CURL_OPTIONS=('-Ls' '-A' "Server-Side Slipstream-Task AVRdude Bootstrap $uaStr")
	curl "${CURL_OPTIONS[@]}" -o /etc/avrdude.conf https://wpsd-swd.w0chp.net/WPSD-SWD/DVMega-Cast/raw/branch/master/etc/avrdude.conf
    fi
    # remove legacy stuff
    if [ -f '/usr/local/cast/etc/preset.txt' ] ; then
        rm -f /usr/local/cast/etc/preset.txt
    fi

    # ensure configs always have proper perms
    chmod 775 /usr/local/cast/etc
    chown -R www-data:pi-star /usr/local/cast/etc
    chmod 664 /usr/local/cast/etc/*

    # www is a symlink so get main perms setup
    chmod 775 /opt/cast/usr-local-cast-www
    chmod 775 /opt/cast/usr-local-cast-www/cast-firmware/fw
    chown -R www-data:www-data /opt/cast/usr-local-cast-www
fi

# Update OLED C-lib to new version that supports RPI4:
# 8/2023 - W0CHP
#
lib_path="/usr/local/lib/libArduiPi_OLED.so.1.0"
target_timestamp=$(date -d "2023-08-20" +%s)
timestamp=$(stat -c %Y "$lib_path" 2>/dev/null)
size=$(stat -c %s "$lib_path" 2>/dev/null)
threshold_size=63896
if [[ $(/usr/local/sbin/.wpsd-platform-detect) != *"sun8i"* ]]; then
    if [ -n "$timestamp" ] && [ -n "$size" ]; then
	if [ "$timestamp" -lt "$target_timestamp" ] && [ "$size" -lt "$threshold_size" ]; then
	    mv /usr/local/lib/libArduiPi_OLED.so.1.0 /usr/local/lib/libArduiPi_OLED.so.1.0.bak
	    rm -f /usr/local/lib/libArduiPi_OLED.so.1
 	    declare -a CURL_OPTIONS=('-Ls' '-A' "libArduiPi_OLED.so updater $uaStr")
	    curl "${CURL_OPTIONS[@]}" -o /usr/local/lib/libArduiPi_OLED.so.1.0 https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/libArduiPi_OLED.so.1.0
	    ln -s /usr/local/lib/libArduiPi_OLED.so.1.0 /usr/local/lib/libArduiPi_OLED.so.1
	    systemctl restart mmdvmhost.service
        else
	    :
        fi
    else
	echo "$lib_path not found or unable to get its information."
    fi
fi
# fix for weird symlink issue
libOLEDlibsymlink="libArduiPi_OLED.so.1"
libOLEDoldTarget="libArduiPi_OLED.so.1.0.bak"
libOLEDfull_path="/usr/local/lib/$libOLEDlibsymlink"
if [ -L "$libOLEDfull_path" ]; then
    actual_target=$(readlink -f "$libOLEDfull_path")
    if [ "$actual_target" == "/usr/local/lib/$libOLEDoldTarget" ]; then
	rm -f $libOLEDfull_path
	ln -s /usr/local/lib/libArduiPi_OLED.so.1.0 /usr/local/lib/libArduiPi_OLED.so.1
        systemctl restart mmdvmhost.service
    fi
fi
#

# avahi tweak
#
# 6/2024 W0CHP
#
if grep -q 'publish-aaaa-on-ipv4=yes' /etc/avahi/avahi-daemon.conf  ; then
    declare -a CURL_OPTIONS=('-Ls' '-A' "Avahi conf Installer (slipstream) $uaStr")
    curl "${CURL_OPTIONS[@]}" https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/avahi-daemon.conf -o /etc/avahi/avahi-daemon.conf
    systemctl restart avahi-daemon.service
fi
#

# Update /etc/issue - 9/2023 & 1/5/2024 W0CHP
#
if ! grep -q 'This is\.\.\.' /etc/issue ; then
    declare -a CURL_OPTIONS=('-Ls' '-A' "/etc/issue updater (slipstream) $uaStr")
    curl "${CURL_OPTIONS[@]}" -o /etc/issue https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/issue
fi
#

#
# WiFi Reg. Domain for Bookworm and bullseye
# 2/1/2024 - W0CHP
#
if [ ! -f '/usr/local/etc/regulatory.txt' ] ; then
    declare -a CURL_OPTIONS=('-Ls' '-A' "WiFi Reg. Domain Installer (slipstream) $uaStr")
    curl "${CURL_OPTIONS[@]}" -o /usr/local/etc/regulatory.txt https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/regulatory.txt
fi
#

#
# dnsmasq config check - 2/9/2024
if ! grep -q 'wpsd' /etc/dnsmasq.conf ; then
    declare -a CURL_OPTIONS=('-Ls' '-A' "dnsmasq config installer (slipstream) $uaStr")
    curl "${CURL_OPTIONS[@]}" -o /etc/dnsmasq.conf https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/dnsmasq.conf
    systemctl restart dnsmasq
fi
#

# grab and cache latest WPSD hashes
conn_check

# 
# 7/2024 W0CHP: terrible bug in Debian bullseye TZdata 2024; missing/corrupted zones...force working version
#
if [ "${OS_VER}" -lt "12" ] ; then # only for bullseye
    desired_version="2021a-1+deb11u10"
    installed_version=$(dpkg-query -W -f='${Version}' tzdata 2>/dev/null)
    if [ "$installed_version" == "$desired_version" ]; then
	: # working version already installed. bail.
    else # install working version
	declare -a CURL_OPTIONS=('-Ls' '-A' "Server-Side Slipstream-Task TZdata Bootstrap $uaStr")
	curl "${CURL_OPTIONS[@]}" https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/tzdata.deb -o /tmp/tzdata.deb
	dpkg -i --force-all /tmp/tzdata.deb
	apt-mark hold tzdata
    fi
fi
#

#
# 12/2024 W0CHP: Hold BW files for wifi fix
#
if [ "${OS_VER}" -eq "12" ] ; then
    apt-mark hold \
        initramfs-tools-core \
        initramfs-tools \
	linux-headers-rpi-v6 \
	linux-headers-rpi-v7 \
	linux-headers-rpi-v7l \
	linux-image-rpi-v6 \
	linux-image-rpi-v7 \
	linux-image-rpi-v7l \
	linux-image-rpi-v8 \
	linux-libc-dev \
	raspberrypi-net-mods \
	raspberrypi-sys-mods \
	raspi-config \
	raspi-firmware \
	rpi-eeprom > /dev/null 2>&1
fi
#

#
# 8/24 W0CHP: bw missing root host file fix
#
cust_host_files=(
    "APRSHosts.txt"
    "DCS_Hosts.txt"
    "DExtra_Hosts.txt"
    "DMR_Hosts.txt"
    "DPlus_Hosts.txt"
    "M17Hosts.txt"
    "NXDNHosts.txt"
    "P25Hosts.txt"
    "XLXHosts.txt"
    "YSFHosts.txt"
)
directory="/root"
for file in "${cust_host_files[@]}"; do
    filepath="$directory/$file"
    if [ ! -f "$filepath" ]; then
        touch "$filepath"
	chown www-data:www-data "$filepath"
    fi
done
#

#
# Empty custom host file fix: W0CHP 8/24
#
files=(
    "/root/APRSHosts.txt"
    "/root/DCS_Hosts.txt"
    "/root/DExtra_Hosts.txt"
    "/root/DMR_Hosts.txt"
    "/root/DPlus_Hosts.txt"
    "/root/M17Hosts.txt"
    "/root/NXDNHosts.txt"
    "/root/P25Hosts.txt"
    "/root/XLXHosts.txt"
    "/root/YSFHosts.txt"
)
for file in "${files[@]}"; do
    if [ -f "$file" ]; then 
        if [ ! -s "$file" ]; then 
            echo "#" > "$file" 
        else
	    :
        fi
    else
	:
    fi
done

# ensure AX.25 is in mmdvmhost
if ! grep -q "\[AX\.25\]" "/etc/mmdvmhost"; then
  cat <<EOL >> "/etc/mmdvmhost"

[AX.25]
Enable=0
TXDelay=300
RXTwist=6
SlotTime=30
PPersist=128
Trace=0

[AX.25 Network]
Enable=0
Port=/dev/ttyp7
Speed=9600
Debug=0
EOL
fi

# bootstrap sbin
#repo_path="/usr/local/sbin"
#cd "$repo_path" || { echo "Failed to change directory to $repo_path"; exit 1; }
#git update-index --assume-unchanged pistar-firewall
#GIT_HTTP_CONNECT_TIMEOUT="10" GIT_HTTP_USER_AGENT="Server-Side sbin Update bootstrap ${gitUaStr}" git pull origin master

# new auto task framweork: 10/24 W0CHP
if systemctl is-enabled wpsd-running-tasks.timer &>/dev/null && systemctl is-enabled wpsd-nightly-tasks.timer &>/dev/null; then
    : # skip
else
    if [[ -f /usr/local/sbin/.wpsd-nightly-tasks ]] || [[ -f /usr/local/sbin/.wpsd-running-tasks ]]; then

        curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-nightly-tasks.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-nightly-tasks.service
        curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-nightly-tasks.timer https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-nightly-tasks.timer
        curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-running-tasks.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-running-tasks.service
        curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-running-tasks.timer https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-running-tasks.timer
        systemctl daemon-reload

        systemctl enable wpsd-running-tasks.timer
        systemctl enable wpsd-nightly-tasks.timer

        systemctl start wpsd-running-tasks.timer
        systemctl start wpsd-nightly-tasks.timer
    fi

    if grep -q "mount -o remount,rw / && cd / && " /etc/crontab; then
        sed -i 's/mount -o remount,rw \/ && cd \/ && //g' /etc/crontab

    fi
    if grep -q "cd / && " /etc/crontab; then
        sed -i 's/cd \/ && //g' /etc/crontab
    fi

    if [[ -f /etc/cron.hourly/pistar-hourly ]]; then
        rm -f /etc/cron.hourly/pistar-hourly
    fi

    if [[ -f /etc/cron.daily/pistar-daily ]]; then
        rm -f /etc/cron.daily/pistar-daily
    fi

    systemctl restart cron
fi
if systemctl is-enabled wpsd-running-tasks.timer &>/dev/null && systemctl is-enabled wpsd-nightly-tasks.timer &>/dev/null; then
    if grep -q "cd / && " /etc/crontab; then
        sed -i 's/cd \/ && //g' /etc/crontab
    fi

    RC_LOCAL="/etc/rc.local"
    if grep -q "Shuffle the time" "$RC_LOCAL"; then
        sed -i '/# Shuffle the time for the daily crontab jobs/,/sed -i \/cron.daily/c ${cronMins} ${cronHours}  \* \* \*   root    mount -o remount,rw \/ && cd \/ && run-parts --report \/etc\/cron.daily/d' "$RC_LOCAL"
    fi
fi
if ! grep -q 'Type=oneshot' /etc/systemd/system/wpsd-nightly-tasks.service ; then
    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-nightly-tasks.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-nightly-tasks.service
    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-running-tasks.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-running-tasks.service
    systemctl daemon-reload
fi
if grep -q 'nightly' /etc/systemd/system/wpsd-running-tasks.service ; then
    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-running-tasks.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-running-tasks.service
fi
if grep -q 'AccuracySec' /etc/systemd/system/wpsd-running-tasks.timer ; then
    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-running-tasks.timer https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-running-tasks.timer
    systemctl daemon-reload
    systemctl restart wpsd-running-tasks.timer
fi
if grep -q 'running' /etc/systemd/system/wpsd-nightly-tasks.service ; then
    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-nightly-tasks.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-nightly-tasks.service
fi
if systemctl is-enabled wpsd-cache.timer &>/dev/null; then
    : # skip
else
    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-cache.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-cache.service
    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-cache.timer https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-cache.timer

    systemctl daemon-reload

    systemctl enable wpsd-cache.timer
    systemctl start wpsd-cache.timer
fi
if grep -q 'Conflicts' /etc/systemd/system/wpsd-cache.service ; then
    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-cache.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-cache.service
    systemctl daemon-reload
fi
if [ -f '/etc/systemd/system/wpsd-nigjtly-tassk.service' ]; then
    rm -rf /etc/systemd/system/wpsd-nigjtly-tassk.service
    systemctl daemon-reload
fi
if [ -f '/etc/systemd/system/wpsd-nightly-tassk.service' ]; then
    rm -rf /etc/systemd/system/wpsd-nightly-tassk.service
    systemctl daemon-reload
fi
# end new auto-task framework

# new auto hostfile framweork: 11/24 W0CHP
if systemctl is-enabled wpsd-hostfile-update.timer &>/dev/null; then
    : # skip
else
    if [[ ! -f /etc/systemd/system/wpsd-hostfile-update.timer ]]; then

        curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-hostfile-update.timer https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-hostfile-update.timer
        curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-hostfile-update.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-hostfile-update.service
        systemctl daemon-reload

        systemctl enable wpsd-hostfile-update.timer
        systemctl start wpsd-hostfile-update.timer
    fi
fi
# end auto hostfiles

# DVMega sun8i stuff
if [[ -f "$armbian_env_file" ]]; then
    # ensure wiringpi is installed
    if ls /usr/local/lib/libwiringPi.so* >/dev/null 2>&1 || [ -f '/usr/local/bin/gpio' ] ; then
        :
    else
        cd /root
        git clone https://github.com/WiringPi/WiringPi.git
        cd WiringPi
        bash ./build
        cd .. && rm -rf WiringPi
    fi
    # ensure we reset the dvmega modems:
    if [[ $(/usr/local/sbin/.wpsd-platform-detect) == *"sun8i"* ]] && [ "$castResult" == "true" ]; then
new_block=$(cat <<'EOF'
# fix the gpio's to avoid unwanted programming of the radio
sudo gpio mode 3 out
sudo gpio mode 4 out
sudo gpio write 4 0
sudo gpio write 3 0
sleep 1
sudo gpio write 3 1

EOF
)
        if ! grep -q "sudo gpio write 3 1" /etc/rc.local; then
            echo "$new_block" > /tmp/new_block.txt
            sed -i "/# start running tasks/r /tmp/new_block.txt" /etc/rc.local
            rm /tmp/new_block.txt
        fi
    fi
fi

# display fixes
if grep -q 'Display=0' /etc/mmdvmhost ; then
    sed -i 's/Display=0/Display=None/g' /etc/mmdvmhost
fi
if grep -q 'Display=0' /etc/mmdvmhost ; then
    sed -i 's/Display=NEXTION/Display=Nextion/g' /etc/mmdvmhost
fi

# ensure avahi loads BEFORE NextionDriver, as Lucas, AE0LI, found that avahi likes to bind to any random port, which can cause a Transparent Data port conflict
#if ! grep -q "avahi" /lib/systemd/system/nextiondriver.service ; then
if grep -q "avahi" /lib/systemd/system/nextiondriver.service ; then
    #sed -i 's/^Before=timers.target$/Before=avahi-daemon.socket avahi-daemon.service timers.target/' /lib/systemd/system/nextiondriver.service
    sed -i 's/^Before=.*/Before=timers.target/' /lib/systemd/system/nextiondriver.service
    systemctl daemon-reload
    systemctl restart avahi-daemon.socket
    systemctl restart avahi-daemon.service
fi

# install new nx driver shutdown service
if [ "${osName}" = "bookworm" ] ; then 
    if [ ! -f '/etc/systemd/system/nextiondriver-shutdown.timer' ] || ! grep -q 'Bookworm' /etc/systemd/system/nextiondriver-shutdown.service || grep -qi 'not found' /etc/systemd/system/nextiondriver-shutdown.service ; then
	curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/nextiondriver-shutdown.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/nextiondriver-shutdown.service-bookworm
	curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/nextiondriver-shutdown.timer https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/nextiondriver-shutdown.timer
	systemctl daemon-reload
	systemctl stop nextiondriver-shutdown.service
	systemctl disable nextiondriver-shutdown.service
	systemctl enable nextiondriver-shutdown.timer
	systemctl restart nextiondriver-shutdown.timer
	systemctl restart mmdvmhost.service
    fi
    if grep -q 'WantedBy=final.target' /etc/systemd/system/nextiondriver-shutdown.service ; then
	curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/nextiondriver-shutdown.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/nextiondriver-shutdown.service-bookworm
	systemctl daemon-reload
	systemctl stop nextiondriver-shutdown.service
	systemctl disable nextiondriver-shutdown.service
	systemctl enable nextiondriver-shutdown.timer
	systemctl restart nextiondriver-shutdown.timer
	systemctl restart mmdvmhost.service
    fi
    if ! grep -q 'poweroff.target' /etc/systemd/system/nextiondriver-shutdown.service ; then
	curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/nextiondriver-shutdown.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/nextiondriver-shutdown.service-bookworm
	systemctl daemon-reload
	systemctl stop nextiondriver-shutdown.service
	systemctl disable nextiondriver-shutdown.service
	systemctl enable nextiondriver-shutdown.timer
	systemctl restart nextiondriver-shutdown.timer
	systemctl restart mmdvmhost.service
    fi
else
    if [ ! -f '/etc/systemd/system/nextiondriver-shutdown.timer' ] || ! grep -q 'Bullseye' /etc/systemd/system/nextiondriver-shutdown.service || grep -qi 'not found' /etc/systemd/system/nextiondriver-shutdown.service ; then
	curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/nextiondriver-shutdown.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/nextiondriver-shutdown.service-bullseye
	curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/nextiondriver-shutdown.timer https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/nextiondriver-shutdown.timer
	systemctl daemon-reload
	systemctl stop nextiondriver-shutdown.service
	systemctl disable nextiondriver-shutdown.service
	systemctl enable nextiondriver-shutdown.timer
	systemctl restart nextiondriver-shutdown.timer
	systemctl restart mmdvmhost.service
    fi
fi

# dash prefs migrator
PISTAR_FILE="/etc/pistar-release"
DASHBOARD_CONFIG="/etc/WPSD-Dashboard-Config.ini"
if [ -f "/etc/pistar-release" ]; then
    phonetic_line=$(grep '^PhoneticCallsigns =' "$PISTAR_FILE")
    call_provider_line=$(grep '^CallLookupProvider =' "$PISTAR_FILE")
    if [ -n "$phonetic_line" ]; then
        phonetic_value="$phonetic_line"
        sed -i '/^PhoneticCallsigns =/d' "$PISTAR_FILE"
        if ! grep -q '^PhoneticCallsigns =' "$DASHBOARD_CONFIG"; then
            echo "$phonetic_value" >> "$DASHBOARD_CONFIG"
        fi
    fi
    if [ -n "$call_provider_line" ]; then
        lookup_value="$call_provider_line"
        sed -i '/^CallLookupProvider =/d' "$PISTAR_FILE"
        if ! grep -q '^CallLookupProvider =' "$DASHBOARD_CONFIG"; then
            echo "$call_provider_line" >> "$DASHBOARD_CONFIG"
        fi
    fi
fi
# legacy config migration
legacy_config_php="/var/www/dashboard/config/config.php"
legacy_language_php="/var/www/dashboard/config/language.php"
legacy_ircddblocal_php="/var/www/dashboard/config/ircddblocal.php"
new_config="/etc/WPSD-Dashboard-Config.ini"
if [[ ! -f "$new_config" || ! -s "$new_config" ]]; then
    echo "[WPSD]" > "$new_config"
    echo "Callsign = " >> "$new_config"
    echo "Timezone = " >> "$new_config"
    echo "DashLanguage = " >> "$new_config"
    echo "TimeFormat = " >> "$new_config"
    echo "UpdateNotifier = " >> "$new_config"
fi
time_format=$(grep -oP "define\('TIME_FORMAT', '\K[0-9]+" "$legacy_config_php")
auto_update_check=$(grep -oP "define\('AUTO_UPDATE_CHECK', '\K\w+" "$legacy_config_php")
timezone=$(grep -oP "date_default_timezone_set\('\K[^']+" "$legacy_config_php")
pistar_language=$(grep -oP "pistarLanguage='\K[^']+" "$legacy_language_php")
callsign=$(grep -oP "callsign='\K[^']+" "$legacy_ircddblocal_php")
if [[ -z "$callsign" ]]; then
    :
else
    # Update the new config file with the extracted values
    if [[ -n "$callsign" ]]; then
        sed -i "s|^Callsign = .*|Callsign = $callsign|" "$new_config"
    fi
    if [[ -n "$time_format" ]]; then
        sed -i "s|^TimeFormat = .*|TimeFormat = $time_format|" "$new_config"
    fi
    if [[ -n "$auto_update_check" ]]; then
        sed -i "s|^UpdateNotifier = .*|UpdateNotifier = $auto_update_check|" "$new_config"
    fi
    if [[ -n "$timezone" ]]; then
        sed -i "s|^Timezone = .*|Timezone = $timezone|" "$new_config"
    fi
    if [[ -n "$pistar_language" ]]; then
        sed -i "s|^DashLanguage = .*|DashLanguage = $pistar_language|" "$new_config"
    fi
fi
MMDVMCALL=$( grep -oP '^Callsign=\K.*' /etc/mmdvmhost | head -n 1 )
CONFIGCALL=$( grep -oP '^Callsign=\K.*' $new_config)
if [[ "$CONFIGCALL" != "$MMDVMCALL" ]] ; then
    sed -i "s|^Callsign = .*|Callsign = $MMDVMCALL|" "$new_config"
fi
# Function to check if any of the specified keys are empty
check_empty_keys() {
    local empty_keys=0

    if [ -f "$DASHBOARD_CONFIG" ]; then
        for key in Callsign Timezone DashLanguage TimeFormat UpdateNotifier PhoneticCallsigns CallLookupProvider; do
            if ! grep -qE "^${key} = .+" "$DASHBOARD_CONFIG"; then
                empty_keys=1
                break
            fi
        done
    fi

    echo "$empty_keys"
}
# Function to check if the specified keys exist in the INI file
check_key_existence() {
    local missing_keys=0

    if [ -f "$DASHBOARD_CONFIG" ]; then
        for key in Callsign Timezone DashLanguage TimeFormat UpdateNotifier PhoneticCallsigns CallLookupProvider; do
            if ! grep -qE "^${key} =" "$DASHBOARD_CONFIG"; then
                missing_keys=1
                break
            fi
        done
    else
        missing_keys=1
    fi

    echo "$missing_keys"
}

if [ ! -f "$DASHBOARD_CONFIG" ] || [ "$(check_key_existence)" -eq 1 ] || [ "$(check_empty_keys)" -eq 1 ]; then
    cat > "$DASHBOARD_CONFIG" <<EOF
[WPSD]
Callsign = ${MMDVMCALL}
Timezone = America/Chicago
DashLanguage = english_us
TimeFormat = 12
UpdateNotifier = true
PhoneticCallsigns = 0
CallLookupProvider = QRZ
EOF
fi
if ! grep -q 'OptIntoUserMap' "$DASHBOARD_CONFIG" ; then
    echo "OptIntoUserMap = false" >> "$DASHBOARD_CONFIG"
fi

# release migrator
source_file="/etc/pistar-release"
destination_file="/etc/WPSD-release"
if [[ ! -f "$destination_file" ]]; then
    while IFS= read -r line; do
        if [[ "$line" == "[Pi-Star]" ]]; then
            echo "[WPSD]" >> "$destination_file"
        else
            echo "$line" >> "$destination_file"
        fi
    done < "$source_file"
fi
if grep -q 'WPSDrelease' /var/www/dashboard/includes/messages.php ; then
    if [[ -f "$destination_file" && -n "$destination_file" ]]; then
        rm -rf "$source_file"
    fi
fi
patterns=(
    "# Update the Kernel version"
    "_KernelVer="
    "_MMDVMHostVer="
    "mount -o remount,rw /"
    "sed -i \"/kernel/c kernel = \$_KernelVer\""
    "sed -i \"/MMDVMHost/c MMDVMHost = \$_MMDVMHostVer\""
)
if grep -q '# Update the Kernel version' /etc/rc.local ; then
    for pattern in "${patterns[@]}"; do
        sed -i "\|$pattern|d" /etc/rc.local
    done
fi

# css migrator
if [ -f '/etc/pistar-css.ini' ]; then
    cp -a /etc/pistar-css.ini /etc/wpsd-css.ini
fi
if grep -q 'found' /etc/wpsd-css.ini ; then
    cp -a /etc/pistar-css.ini /etc/wpsd-css.ini
fi
if [ -f '/INI_FILE' ]; then
    rm -rf /INI_FILE
fi
#if [[ -f "/etc/wpsd-css.ini" && -f "/etc/pistar-css.ini" ]] && cmp -s "/etc/wpsd-css.ini" "/etc/pistar-css.ini"; then
    #rm -rf /etc/pistar-css.ini
#fi

# Check if the fake-hwclock package is installed
if dpkg -l | grep -q "^ii  fake-hwclock"; then
    sudo apt-get remove --purge -y fake-hwclock
fi
if grep -q "flock -n /run/lock/ntpdate /usr/sbin/ntpdate-debian -s -b" /etc/rc.local; then
    sed -i "/# Print the IP address/,/fi/d" /etc/rc.local
fi

if grep -q 'iface = Iface' /etc/WPSD-release ; then
    systemctl stop wpsd-cache.timer
    rm -rf /etc/WPSD-release
    rm -rf /usr/local/etc/.WPSD-release
    systemctl start wpsd-cache.timer
fi

# ensure new web ini and css ini is in each stored profile
SOURCE_FILE="/etc/WPSD-Dashboard-Config.ini"
CSS_SOURCE_FILE="/etc/wpsd-css.ini"
BASE_DIR="/etc/WPSD_config_mgr"
if [[ -f "$SOURCE_FILE" ]]; then
    for dir in "$BASE_DIR"/*/; do
        if [[ -d "$dir" && ! -f "$dir/WPSD-Dashboard-Config.ini" ]]; then
            cp "$SOURCE_FILE" "$dir"
        fi
    done
fi
if [[ -f "$CSS_SOURCE_FILE" ]]; then
    for dir in "$BASE_DIR"/*/; do
        if [[ -d "$dir" && ! -f "$dir/wpsd-css.ini" ]]; then
            cp "$CSS_SOURCE_FILE" "$dir"
        fi
    done
    for dir in "$BASE_DIR"/*/; do
	if [[ -d "$dir" && -f "$dir/pistar-css.ini" ]]; then
	    rm "$dir/pistar-css.ini"
	fi
    done
fi

# new first boot logic
file="/etc/rc.local"
check_string=".wpsd-first-boot"
insert_before="# Generate"
new_block="if [ ! -f '/boot/.WPSD_Booted' ] ; then
    /usr/local/sbin/.wpsd-first-boot
fi"
#if ! grep -q "$check_string" "$file"; then
#    sed -i "/$insert_before/i $new_block" "$file"
#fi
if grep -q "$check_string" "$file"; then
    awk '
BEGIN { found = 0 }
/^if \[ ! -f '\''\/boot\/\.WPSD_Booted'\'' \] ; then$/ { found = 1; next }
found && /^\s+\/usr\/local\/sbin\/\.wpsd-first-boot$/ { next }
found && /^fi$/ { found = 0; next }
!found { print }
' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
fi

# cron
if `systemctl status cron.service | grep -q masked` ; then
    systemctl unmask cron.service
    systemctl enable cron.service
    systemctl restart cron.service
fi

# 11/2024... tweak from Lucas, AE0LI, @ BC; This is to prevent the "Access Code Declined" message from BrandMeister when using remote commands by diverting it to a local TG that won't pass to the network.
ini_file="/etc/dmrgateway"
section="[DMR Network 1]"
check_string="PCRewrite1=2,9999991,2,1,9"
insert_after="PCRewrite0=2,94000,2,4000,1001"
if ! grep -q 'PCRewrite1=2,9999991,2,1,9' "$ini_file" ; then
    awk -v section="$section" \
        -v check="$check_string" \
        -v insert="$insert_after" '
BEGIN {
    in_section = 0
    check_exists = 0
}
/^\[/ {
    # If we leave the section and the line wasn’t found, stop tracking
    if (in_section && check_exists == 0) {
        check_exists = 1
    }
    in_section = ($0 == section)
}
in_section && $0 == check {
    check_exists = 1
}
{
    print
}
in_section && $0 == insert && check_exists == 0 {
    print check
    check_exists = 1
}
    ' "$ini_file" > "${ini_file}.tmp"
    mv "${ini_file}.tmp" "$ini_file"
fi

# nginx perf
if grep -q 'error_log /var/log/nginx/error.log;' /etc/nginx/nginx.conf ; then
    sed -i 's|/var/log/nginx/error.log;|/dev/null;|g' /etc/nginx/nginx.conf
    systemctl reload nginx.service
fi
if grep -q 'error_log off;' /etc/nginx/nginx.conf ; then
    sed -i 's|error_log off;|error_log /dev/null;|g' /etc/nginx/nginx.conf
    systemctl reload nginx.service
fi
if [ -f '/usr/share/nginx/off' ];then
    rm -rf /usr/share/nginx/off
fi
if [ -f '/usr/share/nginx/on' ];then
    rm -rf /usr/share/nginx/on
fi
if [ "${osName}" = "bookworm" ]; then
    if grep -q 'log_errors = On' /etc/php/8.2/fpm/php.ini ; then
	sed -i 's/log_errors = On/log_errors = Off/g' /etc/php/8.2/fpm/php.ini
	systemctl restart php8.2-fpm.service
    fi
    if grep -q 'error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT' /etc/php/8.2/fpm/php.ini ; then
	sed -i 's/error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT/error_reporting = 0/g' /etc/php/8.2/fpm/php.ini
	systemctl restart php8.2-fpm.service
    fi
else
    if grep -q 'log_errors = On' /etc/php/7.4/fpm/php.ini ; then
	sed -i 's/log_errors = On/log_errors = Off/g' /etc/php/7.4/fpm/php.ini
	systemctl restart php7.4-fpm.service
    fi
    if grep -q 'error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT' /etc/php/7.4/fpm/php.ini ; then
	sed -i 's/error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT/error_reporting = 0/g' /etc/php/7.4/fpm/php.ini
	systemctl restart php7.4-fpm.service
    fi
fi

# flaps
if [ -f '/home/pi-star/sudo' ] ; then 
    rm -rf /home/pi-star/sudo
fi

# modem reset unit file migration
if [ ! -f "$armbian_env_file" ] ; then #rpis
    if [ ! -f /etc/systemd/system/wpsd-modemreset.service ] ; then
	if grep -q 'wpsd-modemreset boot' /etc/rc.local ; then 
	    sed -i '/\/usr\/local\/sbin\/wpsd-modemreset boot/d' /etc/rc.local
	fi
	curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-modemreset.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-modemreset.service
	systemctl daemon-reload
	systemctl enable wpsd-modemreset.service
    fi
    if [ -f /etc/systemd/system/wpsd-modemreset.service ] ; then #  oops
	if grep -q 'nextiondriver' /etc/systemd/system/wpsd-modemreset.service ; then
	    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-modemreset.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-modemreset.service
            systemctl daemon-reload
            systemctl enable wpsd-modemreset.service
        fi
    fi
else # nano pis and euronodes
    if [ ! -f /etc/systemd/system/wpsd-modemreset.service ] ; then
	if [ "$castResult" == "false" ]; then # ignore cast devices
	    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-modemreset.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-modemreset.service-nanopi
	    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/rc.local https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/rc.local-nanopi
	    systemctl daemon-reload
	    systemctl enable wpsd-modemreset.service
	    chmod +x /etc/rc.local
	fi
    fi
    if [ -f /etc/systemd/system/wpsd-modemreset.service ] ; then #  migrate to nanopi-only version
	if [ "$castResult" == "false" ]; then # ignore cast devices
	    if ! grep -q 'ExecStartPre' /etc/systemd/system/wpsd-modemreset.service ; then
		curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-modemreset.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-modemreset.service-nanopi
		systemctl daemon-reload
		systemctl enable wpsd-modemreset.service
	    fi
	    if ! grep -q '202411' /etc/rc.local ; then
		curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/rc.local https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/rc.local-nanopi
		chmod +x /etc/rc.local
	    fi
	fi
    fi
fi

# new dvmega cast init-on-(re-)boot framework
if [ "$castResult" == "true" ]; then
    if [ ! -f /etc/systemd/system/wpsd-cast-init.service ] ; then
	curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-cast-init.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-cast-init.service
	curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/rc.local https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/rc.local-CAST
	systemctl daemon-reload
	systemctl enable wpsd-cast-init.service
	chmod +x /etc/rc.local
    fi
    if [ -f /etc/systemd/system/wpsd-cast-init.service ] ; then
	if ! grep -q 'ExecStop' /etc/systemd/system/wpsd-cast-init.service ; then
	    curl -Ls -A "Auto-Task Installer $uaStr" -o /etc/systemd/system/wpsd-cast-init.service https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/wpsd-cast-init.service
	    systemctl daemon-reload
	    systemctl enable wpsd-cast-init.service
	fi
    fi
fi

# no more fake-hwclock crap
if [ -f '/etc/bash.bash_logout' ] ; then
    if grep -q 'clock' /etc/bash.bash_logout ; then
	echo "history -a" > /etc/bash.bash_logout
    fi
fi

# fix empty display values
FILE="/etc/mmdvmhost"
if grep -q "^Display=$" "$FILE"; then
    sed -i 's/^Display=$/Display=None/' "$FILE"
fi

# motd migration
if grep -q 'wspd-motdgen' /etc/rc.local; then
    sed -i '/wspd-motdgen/d' /etc/rc.local
    sed -i '/^# Generate \/etc\/motd/a \/usr\/local\/sbin\/.wpsd-motdgen' /etc/rc.local
fi
if ! grep -q 'wpsd-motdgen' /etc/rc.local ; then
    sed -i 's/motdgen/wpsd-motdgen/g' /etc/rc.local
fi

# only our motd;
rm -f /etc/update-motd.d/*

# fix bookworm + pi0 w2 wifi issue (RPi BRCM firmware is fuuuucked, so we reduce GPU cycles...wtf?)
if [ "${osName}" = "bookworm" ] &&  [[ $(/usr/local/sbin/.wpsd-platform-detect) == *"Pi Zero 2 W"* ]] ; then
    if ! grep -q 'gpu_freq=100' /boot/firmware/config.txt ; then
	echo "gpu_freq=100" >> /boot/firmware/config.txt
	reboot
    fi
    if [ ! -f '/etc/modprobe.d/brcmfmac.conf' ]; then
	echo "options brcmfmac roamoff=1 feature_disable=0x82000" > /etc/modprobe.d/brcmfmac.conf
	reboot
    fi
fi

declare -a CURL_OPTIONS=('-Ls' '-A' "Server-Side Slipstream-Task Diags Bootstrap $uaStr")
curl "${CURL_OPTIONS[@]}" -o /var/run/.wpsd-diags https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/wpsd-diags
chmod +x /var/run/.wpsd-diags
/var/run/.wpsd-diags  > /dev/null 2>&1

# always +x!
chmod +x /etc/rc.local
# always +r!
chmod 644 /etc/mmdvmhost

exit 0

