#!/bin/bash

source /usr/local/sbin/.wpsd-common-funcs

sudo wpsd-services fullstop
sudo rm -rf /usr/local/sbin
sudo env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD sbin reset (server-side) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr}" git clone https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Scripts.git /usr/local/sbin
sudo rm -rf /usr/local/bin
sudo env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD binary reset (server-side) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr}" git clone https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Binaries.git /usr/local/bin

if [ "$fwState" == "enabled" ]; then
    sudo /usr/local/sbin/wpsd-system-manager -efw
else
    sudo /usr/local/sbin/wpsd-system-manager -dfw
fi

cp -av /var/www/dashboard/config /tmp
rm -rf /var/www/dashboard
sudo env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD sbin reset (server-side) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr}" git clone https://repo.w0chp.net/WPSD-Dev/WPSD-WebCode.git /var/www/dashboard
rm -rf /var/www/dashboard/config
mv -v /tmp/config /var/www/dashboard/

sudo wpsd-services start

echo "WPSD has been reset."

