#!/bin/bash

source /usr/local/sbin/.wpsd-common-funcs

if [ ! -f '/etc/WPSD-release' ] ; then
    cp /etc/pistar-release /etc/WPSD-release
    source /usr/local/sbin/.wpsd-common-funcs
fi

sudo rm -rf /usr/local/sbin
sudo GIT_HTTP_CONNECT_TIMEOUT="10" GIT_HTTP_USER_AGENT="WPSD sbin reset (server-side)" git clone --depth 1 https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Scripts.git /usr/local/sbin

# check if user already has firewall disabled, and if so, ensure it's kept that way.
if [ "$fwState" == "enabled" ]; then
    sudo /usr/local/sbin/wpsd-system-manager -efw
else
    sudo /usr/local/sbin/wpsd-system-manager -dfw
fi

sudo /usr/local/sbin/wpsd-update
